#cloud-config
autoinstall:
    version: 1
    locale: en_US
    user-data:
      disable_root: false
      timezone: US/Eastern
    storage:
        layout:
            name: lvm
            password: BeatArmy
    identity:
        hostname: lnx
        username: ladmin
        password: '$6$iZc7oeKPF28Rc91g$rEdq1f8UUekGUX.fOXN/CV2K8lyaluxnWQfdVR95UGe41l1Y0YC4XV4Hnrm1mvoByAY4gXnKQ5RoPWwnImEKz/'
    apt:
        preserve_sources_list: false
        primary:
        - arches: [default]
          uri: http://us.archive.ubuntu.com/ubuntu/
    packages:
        - ssh
        - aptitude
        - libreoffice
        - clevis
        - clevis-tpm2
        - clevis-luks
        - clevis-initramfs
        - clevis-systemd
    late-commands:
        - sudo apt install -y notepadqq
        - echo "Options = UnsafeLegacyRenegotiation" | sudo tee -a /etc/ssl/openssl.cnf
        - curl apt.cs.usna.edu/ssl/install-ssl-server.sh | bash

