#cloud-config
autoinstall:
    version: 1
    locale: en_US
    timezone: US/Eastern
    storage:
        layout:
            name: lvm
            password: BeatArmy
    identity:
        hostname: lnx
        username: ladmin
        password: '$6$iZc7oeKPF28Rc91g$rEdq1f8UUekGUX.fOXN/CV2K8lyaluxnWQfdVR95UGe41l1Y0YC4XV4Hnrm1mvoByAY4gXnKQ5RoPWwnImEKz/'
    apt:
      primary:
        - arches: [default]
          search:
            - http://archive.ubuntu.com
    packages:
        - ssh
        - libreoffice
        - clevis
        - clevis-tpm2
        - clevis-luks
        - clevis-initramfs
        - clevis-systemd
    late-commands:
        - sudo apt install -y clevis clevis-tpm2 clevis-luks clevis-initramfs clevis-systemd ssh
