#cloud-config
autoinstall:
    version: 1
    locale: en_US
    timezone: US/Eastern
    storage:
        layout:
            name: lvm
            password: BeatArmy
    identity:
        hostname: lnx
        username: ladmin
        password: '$6$iZc7oeKPF28Rc91g$rEdq1f8UUekGUX.fOXN/CV2K8lyaluxnWQfdVR95UGe41l1Y0YC4XV4Hnrm1mvoByAY4gXnKQ5RoPWwnImEKz/'
    apt:
        primary:
        - arches: [default]
          uri: http://us.archive.ubuntu.com/ubuntu/
    ca-certs:
      trusted:
      - |
      -----BEGIN CERTIFICATE-----
MIIHjDCCBXSgAwIBAgITTwABCSFItgaEBYunhQAAAAEJITANBgkqhkiG9w0BAQsF
ADBwMRMwEQYKCZImiZPyLGQBGRYDZWR1MRQwEgYKCZImiZPyLGQBGRYEdXNuYTEX
MBUGCgmSJomT8ixkARkWB2FjYWRlbXkxKjAoBgNVBAMTIVVTTkEgMjAxNyBFbnRl
cnByaXNlIElzc3VpbmcgQ0EgMTAeFw0yMDA1MDExNzA1MTdaFw0yNTA0MzAxNzA1
MTdaMIGAMQswCQYDVQQGEwJVUzERMA8GA1UECBMITWFyeWxhbmQxEjAQBgNVBAcT
CUFubmFwb2xpczENMAsGA1UEChMEVVNOQTEbMBkGA1UEAxMSUGFsbzIuc292LnVz
bmEuZWR1MR4wHAYJKoZIhvcNAQkBFg9paHRlYW1AdXNuYS5lZHUwggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDI5eHzyKmzuY0Z7stknCjcSFwc/FkJIgTM
7tCL0I1Q5twhHxTEykjqUK09eQSR6LnB3a4naUHM0yHNu4GrYk6JzP6OEuC9o7t6
BXS0T4z/1KWSQAhIr6sL+oCq3ue6E0FJwVuigiqbzqg6GuJT8JM7QjWryqTV9T9D
KQKki7SyjnWKIcqYjLfOny4pmTV8mbOPtrSjklqedFtvfoLUm70taAT9UZJYyxOD
zferJ22VpgsnOGA36qGj5iTQWXm2lIMmrzNkO0/gqvbi8P73TKYzOI1D9FoKpNkl
FaBaGRvNl2xG9jp5oCCszFaOAFGJQhERzniF2jsFdEyuPhm4i/P1AgMBAAGjggMM
MIIDCDAdBgNVHQ4EFgQUTh/j48se9z5zAm9qs3YwJ2v0apwwHwYDVR0jBBgwFoAU
ZBX7f9BX9rSM5rvBuUbKKhfSBlEwggFDBgNVHR8EggE6MIIBNjCCATKgggEuoIIB
KoaB2WxkYXA6Ly8vQ049VVNOQSUyMDIwMTclMjBFbnRlcnByaXNlJTIwSXNzdWlu
ZyUyMENBJTIwMSxDTj1DQUEtMDEsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNl
cnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9YWNhZGVteSxE
Qz11c25hLERDPWVkdT9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2Jq
ZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnSGTGh0dHA6Ly9jZHAudXNuYS5l
ZHUvQ2VydERhdGEvVVNOQSUyMDIwMTclMjBFbnRlcnByaXNlJTIwSXNzdWluZyUy
MENBJTIwMS5jcmwwggFBBggrBgEFBQcBAQSCATMwggEvMIHSBggrBgEFBQcwAoaB
xWxkYXA6Ly8vQ049VVNOQSUyMDIwMTclMjBFbnRlcnByaXNlJTIwSXNzdWluZyUy
MENBJTIwMSxDTj1BSUEsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2Vy
dmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1hY2FkZW15LERDPXVzbmEsREM9ZWR1
P2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0
aG9yaXR5MFgGCCsGAQUFBzAChkxodHRwOi8vY2RwLnVzbmEuZWR1L0NlcnREYXRh
L1VTTkElMjAyMDE3JTIwRW50ZXJwcmlzZSUyMElzc3VpbmclMjBDQSUyMDEuY3J0
MBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMA8GA1UdEwEB/wQFMAMBAf8wDgYD
VR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4ICAQBwl/PCocz0uLq0P6UgdKRv
6UJG9wjUuudLhRUWxdkd+mp1hJX/bP4nflh+r/ocZfgJSQaS/3hRN90qCD1quPas
DjjbmnEPIRwn77tQ1E4bNlG10aolmGZJDkp8gRbMoc4aNZOwvYAkVR6fRCecFE7Y
PIR/JGF6fhUozUOKcsDQOpZ2F679J5mle1OnSj2JpRuVk8o02ZrkXmxzJUYnYAoz
+KyLuBRi0al68g0GlKhMG4JwUKzeAie2Ktrb1koWhBWzPBQAJCGgzy09rlTA4oJA
CTvHEUEafXeojCTnXIZ4ngUUznvdzNNjrDm+6ivIcPxgusMX3VHlM3vRXRCBVsIS
Q9GufbnFE0Gs0zjSt+yATDtXHSynrG9/etputs4hhWQl8QBs1laVht07aRE1dtJp
fQ7hiCCiKFnpZTMTKjjSg7f6Ak2cFBSW46Mzo/NIZzC+jkAitMQXHEWuRTpvYpEa
Bg5n0Wk5D5ctwi5VcyVhjG4DJtVbuQALYjgV83UTe139sAjKYfsRq2nXLJ0R7XxD
RKxBGvoHoFwrlHoTR9vYRhMVNRGYp5O8hM4E1NT/2aBAUrNZ1xH8BKN2gXoPQvVL
EG+oe1hBoISurcrFVH7FHxbSZS6n7EDuJXBLzx8+y/WmUDfIpuxyzPWfi4zEYkFA
kkDnlU492q4K4m5zZK4SUw==
-----END CERTIFICATE-----
    packages:
        - ssh
        - libreoffice
        - clevis
        - clevis-tpm2
        - clevis-luks
        - clevis-initramfs
        - clevis-systemd
    late-commands:
        - sudo apt install -y clevis clevis-tpm2 clevis-luks clevis-initramfs clevis-systemd ssh
